# Generated by Django 4.1.7 on 2023-04-26 19:55

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', wagtail.fields.StreamField([('map', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='', label='Имя', max_length=128, required=False)), ('live', wagtail.blocks.BooleanBlock(default=False, help_text='Включение/отключение отображения карты', label='Скрыть', required=False)), ('html', wagtail.blocks.TextBlock(default='', label='<HTML>', required=False))], default='[]'))], blank=True, use_json_field=True, verbose_name='Карта')),
                ('phone', wagtail.fields.StreamField([('phone', wagtail.blocks.StructBlock([('type', wagtail.blocks.ChoiceBlock(choices=[('МТС', 'МТС'), ('A1', 'A1'), ('Life', 'Life'), ('Work', 'Work'), ('Fax', 'Fax')], label='Провайдер')), ('title', wagtail.blocks.CharBlock(default='', label='Имя', max_length=128, required=False)), ('number', wagtail.blocks.CharBlock(default='', help_text='Пример: «+375-29-666-44-22»', label='Номер', max_length=17, required=True)), ('live', wagtail.blocks.BooleanBlock(default=False, help_text='Включение/отключение отображения номера', label='Скрыть', required=False))], default='[]'))], blank=True, use_json_field=True, verbose_name='Телефоны')),
                ('email', wagtail.fields.StreamField([('email', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='', label='Имя', max_length=128, required=False)), ('e_mail', wagtail.blocks.EmailBlock(default='', label='e-mail', max_length=128, required=True))], default='[]'))], blank=True, use_json_field=True, verbose_name='Электронные адреса')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Контакты',
            },
        ),
    ]
