# Generated by Django 4.1.7 on 2023-04-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='address',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='map',
            name='work_time',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Рабочее время'),
        ),
    ]
