# Generated by Django 4.1.7 on 2023-04-28 19:57

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_map_address_map_work_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='address_ico',
            field=models.CharField(blank=True, default='<i class="fa-li fa fa-home launch-show"></i>', max_length=128, verbose_name='ico'),
        ),
        migrations.AddField(
            model_name='map',
            name='work_time_ico',
            field=models.CharField(blank=True, default='<i class="fa-solid fa-clock"></i>', max_length=128, verbose_name='ico'),
        ),
        migrations.AlterField(
            model_name='map',
            name='email',
            field=wagtail.fields.StreamField([('email', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='', label='Имя', max_length=128, required=False)), ('ico', wagtail.blocks.CharBlock(default='<i class="fa-solid fa-envelope"></i>', label='ico', max_length=128, required=False)), ('e_mail', wagtail.blocks.EmailBlock(default='', label='e-mail', max_length=128, required=True))], default='[]'))], blank=True, use_json_field=True, verbose_name='Электронные адреса'),
        ),
        migrations.AlterField(
            model_name='map',
            name='map',
            field=wagtail.fields.StreamField([('map', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='', label='Имя', max_length=128, required=False)), ('live', wagtail.blocks.BooleanBlock(default=False, help_text='Включение/отключение отображения карты', label='Скрыть', required=False)), ('html', wagtail.blocks.TextBlock(default='', help_text='Установите width=100% height=320', label='<HTML>', required=False))], default='[]'))], blank=True, use_json_field=True, verbose_name='Карта'),
        ),
        migrations.AlterField(
            model_name='map',
            name='phone',
            field=wagtail.fields.StreamField([('phone', wagtail.blocks.StructBlock([('type', wagtail.blocks.ChoiceBlock(choices=[('МТС', 'МТС'), ('A1', 'A1'), ('Life', 'Life'), ('Work', 'Work'), ('Fax', 'Fax')], label='Провайдер')), ('ico', wagtail.blocks.CharBlock(default='<i class="fa-li fa fa-phone"></i>', label='ico', max_length=128, required=False)), ('title', wagtail.blocks.CharBlock(default='', label='Имя', max_length=128, required=False)), ('number', wagtail.blocks.CharBlock(default='', help_text='Пример: «+375-29-666-44-22»', label='Номер', max_length=17, required=True)), ('live', wagtail.blocks.BooleanBlock(default=False, help_text='Включение/отключение отображения номера', label='Скрыть', required=False))], default='[]'))], blank=True, use_json_field=True, verbose_name='Телефоны'),
        ),
    ]
