# Generated by Django 4.1.7 on 2023-04-29 12:28

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_map_address_alter_map_address_ico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='brnds',
            field=wagtail.fields.StreamField([('brands', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Имя', label='Имя', max_length=128, required=False)), ('ico', wagtail.blocks.CharBlock(default='<i class="fa-solid fa-envelope"></i>', label='Иконка', max_length=128, required=False)), ('url', wagtail.blocks.URLBlock(default='', label='url', required=True))], default='[]'))], blank=True, use_json_field=True, verbose_name='Социальные сети'),
        ),
    ]
