# Generated by Django 4.1.7 on 2023-04-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_map_brnds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='brnds',
            new_name='brands',
        ),
    ]
