# Generated by Django 4.1.7 on 2023-05-02 05:42

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_rename_brnds_map_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='address_live',
            field=models.BooleanField(default=False, help_text='Включение/отключение отображения онтактов', verbose_name='Скрыть'),
        ),
        migrations.AlterField(
            model_name='map',
            name='brands',
            field=wagtail.fields.StreamField([('brands', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Имя', label='Имя', max_length=128, required=False)), ('ico', wagtail.blocks.CharBlock(default='', label='Иконка', max_length=128, required=False)), ('url', wagtail.blocks.URLBlock(default='', label='url', required=True))], default='[]'))], blank=True, use_json_field=True, verbose_name='Социальные сети'),
        ),
    ]
