# Generated by Django 4.1.7 on 2023-05-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_map_address_live_alter_map_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='brands_live',
            field=models.BooleanField(default=False, help_text='Включение/отключение отображения социальных сетей', verbose_name='Скрыть'),
        ),
        migrations.AlterField(
            model_name='map',
            name='address_live',
            field=models.BooleanField(default=False, help_text='Включение/отключение отображения контактов и карты', verbose_name='Скрыть'),
        ),
    ]
