# Generated by Django 4.1.7 on 2023-04-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(blank=True, choices=[('A1', 'A1'), ('MTС', 'Mtc'), ('Life', 'Life')], max_length=10)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('e_mail', models.EmailField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
