# Generated by Django 4.1.7 on 2023-04-21 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsDesign',
            fields=[
            ],
            options={
                'verbose_name': 'Дизайн',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('navigation.navigationmenusetting',),
        ),
    ]
