# Generated by Django 4.1.7 on 2023-04-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_phoneoperators_phonesnumbers_delete_footer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonesnumbers',
            options={'verbose_name': 'Номер телефона', 'verbose_name_plural': 'Номера телефонов'},
        ),
        migrations.AlterField(
            model_name='phonesnumbers',
            name='operator',
            field=models.CharField(choices=[('A1', 'A1.png'), ('MTС', 'MTС.png'), ('Life', 'Life.png'), ('City', 'City.png')], max_length=16, null=True),
        ),
        migrations.DeleteModel(
            name='PhoneOperators',
        ),
    ]
