# Generated by Django 4.1.7 on 2023-04-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_phonesnumbers_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricMails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_mail', models.CharField(max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Электрическая почта',
                'verbose_name_plural': 'Адреса электрической почты',
            },
        ),
        migrations.AlterField(
            model_name='phonesnumbers',
            name='operator',
            field=models.CharField(choices=[('A1', 'A1'), ('MTС', 'MTС'), ('Life', 'Life'), ('City', 'City')], max_length=16, null=True),
        ),
    ]
