# Generated by Django 4.1.7 on 2023-04-17 10:13

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0009_alter_navigationmenusetting_menu_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationmenusetting',
            name='menu_items',
            field=wagtail.fields.StreamField([('internal_page', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Поумолчанию используется имя страницы.', label='Изменить имя обычного меню', required=False)), ('page', wagtail.blocks.PageChooserBlock(label='Страница')), ('live', wagtail.blocks.BooleanBlock(default=False, help_text='Включение/отключение отображения категории меню', label='Скрыть меню', required=False)), ('anchor', wagtail.blocks.CharBlock(help_text='Для ссылки на определенные элементы страницы. Введите текст привязки без символа «#».', label='Якорь', required=False))])), ('external_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('url', wagtail.blocks.URLBlock()), ('anchor', wagtail.blocks.CharBlock(help_text='Для ссылки на определенные элементы страницы. Введите текст привязки без символа «#».', required=False))])), ('drop_down', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Имя выпадающего меню')), ('live', wagtail.blocks.BooleanBlock(default=False, help_text='Включение/отключение выпадающего меню', label='Скрыть выпадающее меню и подменю', required=False)), ('menu_items', wagtail.blocks.StreamBlock([('page', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Поумолчанию используется имя страницы.', label='Изменить имя обычного меню', required=False)), ('page', wagtail.blocks.PageChooserBlock(label='Страница')), ('live', wagtail.blocks.BooleanBlock(default=False, help_text='Включение/отключение отображения категории меню', label='Скрыть меню', required=False)), ('anchor', wagtail.blocks.CharBlock(help_text='Для ссылки на определенные элементы страницы. Введите текст привязки без символа «#».', label='Якорь', required=False))])), ('external_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('url', wagtail.blocks.URLBlock()), ('anchor', wagtail.blocks.CharBlock(help_text='Для ссылки на определенные элементы страницы. Введите текст привязки без символа «#».', required=False))]))]))]))], use_json_field=True),
        ),
    ]
